config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :users, only: [:new, :index, :show, :destroy]
  resources :orders, ony: [:new, :create, :index]
  post 'users/add_user', to: 'users#add_user'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :manager, class_name: 'User', optional: true
  belongs_to :fixer, class_name: 'User', optional: true
  belongs_to :customer, class_name: 'User'

  validates :address, presence: true
  validates :date, presence: true

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)
    @order.customer = current_user
    @order.fixed = false
    if @order.save
      flash[:notice] = 'Good Job'
      redirect_to orders_path
    else
      render :new
    end
  end

  def index
    @orders = Order.all

    @markers = @orders.geocoded.map do |order|
      {
        lat: order.latitude,
        lng: order.longitude
      }
    end
    
  end

  private

  def order_params
    params.require(:order).permit(:date, :customer, :address, :fixed)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def add_user
    @password = 'password'
    @user = User.new(user_params)
    @user.password = @password
    @user.save
    if @user.save
      redirect_to '/users'
    else
      render 'new'
    end
  end


  def index
    # authorize :user, :manager?
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :address, :manager, :fixer)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cyclone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>

    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/orders/index.html.erb
<div class="orders-content d-flex">
  <div class="order-details" style="width: 100%">
    <h1>Orders index</h1>
    <p><%= link_to "Home", root_path, class: "btn btn-primary" %></p>
    <div class="order-cards">
      <% @orders.each do |order| %>
        <div class="card">
          <p> customer : <%= User.find(order.customer_id).first_name %> <%= User.find(order.customer_id).last_name %></p>
          <p> Address: <%= order.address %></p>
          <p> date : <%= order.date %></p>
          <p> Fixed : <%= order.fixed %></p>
          <p> Fixer : <%= order.fixer_id %></p>
        </div>
        <% end %>
      </div>
  </div>

  <div class="index-map">
    <% if @orders.count > 0 %>
      <div id="map" style="width: 100%; height: 100%;" data-markers="<%= @markers.to_json %>" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
    <% else %>
      <p>No order at this time. Come back later !</p>
    <% end %>
  </div>
</div>

app/views/orders/new.html.erb
<h1>new order</h1> 
 
<%= simple_form_for(@order) do |f| %>
  <%= f.input :address, required: true, label: 'address', input_html: { value: current_user.address } %>
  <%= f.input :date, required: true, as: :datetime %>
  <%= f.button :submit, "submit", class: 'btn btn-primary' %>
<% end %>

<p><%= link_to "Home", root_path, class: "btn btn-danger" %></p>

app/views/pages/home.html.erb
<h1>let's code !</h1>



<% if user_signed_in? %>

  <p>Current role :</p>
    <% if current_user.manager == true && current_user.fixer == false %>
    <p>Manager</p>
  <% elsif current_user.manager == false && current_user.fixer == true %>
    <p>Fixer</p>
  <% else %>
    <p>Customer</p>
  <% end %>

  <p><%= link_to "New User", new_user_path, class: "btn btn-success" %></p>
  <p><%= link_to "Users index", users_path, class: "btn btn-secondary" %></p>
  <p><%= link_to "New order", new_order_path, class: "btn btn-info" %></p>
  <p><%= link_to "Orders", orders_path, class: "btn btn-warning" %></p>
  <p><%= link_to "log out", destroy_user_session_path, class: "btn btn-primary" %></p>
<% else %>
  <%= link_to "Sign in", new_user_session_path, class: "btn btn-danger" %>
<% end %>


<%# Old code above %>

<% if user_signed_in? %>

  <p>Welcome home <%= current_user.first_name %></p>

    <%# manager %>
    <% if current_user.manager == true && current_user.fixer == false %>
      <p>Current role : Manager</p>

      <div class="home-content">
        <div class="home-card">
          <p><%= link_to "Orders", orders_path, class: "btn btn-warning" %></p>
        </div>
        <div class="home-card">
          <p><%= link_to "Users", users_path, class: "btn btn-secondary" %></p>
        </div>
      </div>

    <%# fixer %>
    <% elsif current_user.manager == false && current_user.fixer == true %>
      <p>Current role : Fixer</p>

      <div class="home-content">
        <div class="home-card">
          <p><%= link_to "My orders - TO DO", orders_path, class: "btn btn-warning" %></p>
        </div>
        <div class="home-card">
          <p><%= link_to "My Profile TO-DO", users_path, class: "btn btn-secondary" %></p>
        </div>
      </div>

    <%# customer %>
    <% else %>
      <p>Current role : Customer</p>

      <div class="home-content">
        <div class="home-card">
          <p><%= link_to "My orders - TO DO", orders_path, class: "btn btn-warning" %></p>
        </div>
        <div class="home-card">
          <p><%= link_to "My Profile TO-DO", users_path, class: "btn btn-secondary" %></p>
        </div>
      </div>

    <% end %>

  
<% else %>

  <%= link_to "Sign in", new_user_session_path, class: "btn btn-danger" %>


<% end %>

app/views/shared/_flashes.html.erb
<% if notice %> 
  <div class="alert alert-info alert-dismissible fade show m-1" id="main-image"role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" id="main-image" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/users/index.html.erb
<h1>Users Index</h1>

<div class="user-index d-flex">
  <div style="width: 100%">
    <h3>Customers</h3>
    <% @users.each do |user| %>
      <% if user.manager == false && user.fixer == false %>
        <div class="user-card">
          <p>First name : <%= user.first_name %></p>
          <p>Last name : <%= user.last_name %></p>
          <p><%= link_to "User Details", user_path(user.id), class:"btn btn-danger" %></p>
          <p><%= link_to "Delete", user_path(user.id), method: :delete, data: {confirm: "Are you sure?"}, class:"text-danger" %></p>
        </div>
      <% end %>
    <% end %>
  </div>

  <div style="width: 100%">
    <h3>Fixers</h3>
    <% @users.each do |user| %>
      <% if user.manager == false && user.fixer == true %>
        <div class="user-card">
          <p>First name : <%= user.first_name %></p>
          <p>Last name : <%= user.last_name %></p>
          <p><%= link_to "User Details", user_path(user[:id]), class:"btn btn-danger" %></p>
          <p><%= link_to "Delete", user_path(user[:id]), method: :delete, data: {confirm: "Are you sure?"}, class:"text-danger" %></p>
        </div>
      <% end %>
    <% end %>
  </div>

</div>

<p><%= link_to "Home", root_path, class: "btn btn-primary" %></p>

app/views/users/new.html.erb
<%= simple_form_for(@user, url: url_for(users_add_user_path), method: :post) do |f| %>
  <%= f.error_notification %>
  <div class="form-inputs">
    <%= f.input :first_name,
                required: true,
                autofocus: true,
                label: 'First Name'%>
    <%= f.input :last_name,
                required: true,
                autofocus: true,
                label: 'Last Name'%>
    <%= f.input :address,
                required: true,
                autofocus: true,
                label: 'Address' %>
    <%= f.input :email,
                required: true,
                autofocus: true,
                input_html: { autocomplete: 'email' },
                label: 'Email' %>
    <%= f.input :manager, as: :boolean, checked_value: true, unchecked_value: false %>
    <%= f.input :fixer, as: :boolean, checked_value: true, unchecked_value: false %>
    <%#= f.input :manager,
                as: :radio_buttons,
                #include_blank: false,
                collection: [true, false],
                required: true,
                label: 'Manager',
                autofocus: true %>
    <%#= f.input :fixer,
                as: :select,
                #include_blank: false,
                collection: [true, false],
                required: true,
                label: 'Fixer',
                autofocus: true %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Ajoutez", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/users/show.html.erb
<h1>User show</h1>

<p><%= link_to "Home", root_path, class: "btn btn-primary" %></p>

<p><%= @user.id %></p>
<p><%= @user.first_name %></p>
<p><%= @user.last_name %></p>
<p><%= @user.email %></p>
<p><%= @user.address %></p>

<% if @user.manager == true && @user.fixer == false %>
      <p>Manager</p>
    <% elsif @user.manager == false && @user.fixer == true %>
      <p>Fixer</p>
    <% else %>
      <p>Customer</p>
<% end %>

<p>Orders made :</p>
<p><%= Order.where(customer_id: @user.id).count %></p>

<p>Orders fixed</p>
<p><%= Order.where(fixer_id: @user.id).where(fixed: true).count %></p>